/**
 * Generated by type wsimport -s . http://localhost:1515/WS/Calculadora?wsdl in JAXWS-Calculadora/src/ 
 */

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.ecodeup.com/")
package com.ecodeup.ws;
